{
  ### Environment Parameters
  debug: false,
  mode: inference,
  cuda: true,
  pin_memory: true,
  wandb: false,
  worker: 2,
  CUDA_VISIBLE_DEVICES: '0',

  ### Train Parameters
  model_name: 'FSGNet',
    n_classes: 1,
    in_channels: 3,
    base_c: 64,
  inference_mode: 'segmentation',
  task: 'segmentation',
  dataloader: 'Image2Image_resize',
  criterion: 'DiceBCE',
  input_space: 'RGB',
  input_channel: 3,
  input_size: [1024, 1024],  # DRIVE:608, STARE:704, CHASE_DB1:1024, HRF: 1344

  model_path: 'pretrained/FSGNet-Epoch_918-f1_score_0.7753670181444041.pt',
  val_x_path:   '/lulu_data/data/public/Retina-comb/SCH/all/input',
  val_y_path:   '/lulu_data/data/public/Retina-comb/SCH/all/label',
}
